name: streaming_platform_backend
description: Backend services for the streaming platform
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  postgres: ^2.6.3
  dotenv: ^5.1.0
  shelf: ^1.4.1
  shelf_router: ^1.1.0
  shelf_cors_headers: ^1.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0 